# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885c85771e489ecd1cc12595b77953fd2ff6828b3b7b76a1d78f45e5f5ce276de486219bff0fe4b4db14915ad487ecd3b7c8cada24b3c4c5ace3225d2c330b1b

test:
  secret_key_base: 89ce221acf46faaf0f1c1011fd6b5ec721b35d79fbfe3c643f81fc805903c5c57a755071182a5aeec27bd77dc963fdf5762d241bf010723dd4c011c9a744a3cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
